### ISSUE TITLE
wut is this

### ISSUE THREAD

**Issue by GravityGuy** [thecraptheorist/Cesium#5]
laughing at me for forking by accident xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
laughing at me for forking by accident xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
laughing at me for forking by accident xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by thecraptheorist** [comment]
This isn't for spamming madhav.
Learn how 2 github pls
